services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_net
    restart: on-failure 
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      .env
    depends_on: 
      - mariadb
    networks:
      - inception_net
    restart: on-failure 
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    build: ./requirements/nginx
    image: nginx:inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      .env
    depends_on:
      - wordpress
    networks:
      - inception_net
    restart: on-failure

volumes:
  mariadb:
    name: mariadb_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/vasco/data/mariadb
  wordpress:
    name: wordpress_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/vasco/data/wordpress

networks:
  inception_net:
    name: inception_net
