#! /usr/bin/env bash

USE mysql;
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;
CREATE USER IF NOT EXISTS '$USER'@'%';
CREATE USER IF NOT EXISTS 'ADMIN_USER'@'%';
SET PASSWORD FOR '$USER'@'%' = PASSWORD('$MYSQL_USERD');
SET PASSWORD FOR '$ADMIN_USER'@'%' = PASSWORD('$ADIM_PASSWORD');
GRANT ALL PRIVILEGES ON wordpress.* TO '$USER'@'%';
GRANT ALL PRIVILEGES ON wordpress.* TO 'ADIM_USER'@'%';
FLUSH PRIVILEGES;