/* USE  mysql;
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS ${MYSGL_DATABASE};
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSGL_DATABASE}.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES; */

USE mysql;
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_PASSWORD';
CREATE DATABASE IF NOT EXISTS '$DB_NAME';
CREATE USER IF NOT EXISTS '$DB_USER'@'%';
CREATE USER IF NOT EXISTS '$WORDPRESS_ADMIN'@'%';
SET PASSWORD FOR '$DB_USER'@'%' = PASSWORD('$DB_PASSWORD');
SET PASSWORD FOR '$WORDPRESS_ADMIN'@'%' = PASSWORD('$DB_PASSWORD');
GRANT ALL PRIVILEGES ON wordpress.* TO '$DB_USER'@'%';
GRANT ALL PRIVILEGES ON wordpress.* TO '$WORDPRESS_ADMIN'@'%';
FLUSH PRIVILEGES;